//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMono1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost
    {
        public int BlogPostId { get; set; }
        public string BlogPostTitle { get; set; }
        public string BlogPostBody { get; set; }
        public int BlogPostPhotoId { get; set; }
    
        public virtual Photo Photo { get; set; }
    }
}
