//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMono1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFeedback
    {
        public int FeedbackId { get; set; }
        public string FeedbackSenderName { get; set; }
        public string FeedbackText { get; set; }
        public string FeedbackSenderRole { get; set; }
        public int FeedbackSenderPhotoId { get; set; }
    
        public virtual Photo Photo { get; set; }
    }
}
