//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMono1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public int TeamMemberId { get; set; }
        public string TeamMemberName { get; set; }
        public int TeamMemberPhotoId { get; set; }
        public int TeamMemberPositionId { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Position Position { get; set; }
    }
}
